#!/bin/sh

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$remote_oid" = "$zero"
	then
		# New branch, examine all commits
		range="$local_oid"
	else
		# Update to existing branch, examine new commits
		range="$remote_oid..$local_oid"
	fi

	commitList=$(git rev-list "$range")

	for commit in $commitList; do
		if ! git verify-commit $commit >/dev/null 2>&1; then
			echo -e "\033[31merror: коммит $commit не подписан\033[0m"
			
			exit 1
		fi
	done
done

exit 0